// ============================================================
//  items-db.js — Base de datos de items de Lineage 2 Reborn
//  Categorías: weapon, armor, jewelry, material, consumable,
//              recipe, scroll, special, adena
// ============================================================

export const L2_ITEMS = [
    // ── ADENA ────────────────────────────────────────────────
    { id: 1, name: "Adena", category: "adena", grade: "", type: "currency" },

    // ── ARMAS — Espadas 1H ───────────────────────────────────
    { id: 100, name: "Sword of Limit", category: "weapon", grade: "D", type: "sword" },
    { id: 101, name: "Eminence Bow", category: "weapon", grade: "D", type: "bow" },
    { id: 102, name: "Shadow Sword", category: "weapon", grade: "C", type: "sword" },
    { id: 103, name: "Gastraphetes", category: "weapon", grade: "C", type: "bow" },
    { id: 104, name: "Homunkulus's Sword", category: "weapon", grade: "C", type: "sword" },
    { id: 105, name: "Sword of Valhalla", category: "weapon", grade: "C", type: "sword" },
    { id: 106, name: "Elven Long Sword", category: "weapon", grade: "C", type: "sword" },
    { id: 107, name: "Art of Battle Axe", category: "weapon", grade: "C", type: "blunt" },
    { id: 108, name: "Crystalized Ice Bow", category: "weapon", grade: "C", type: "bow" },
    { id: 109, name: "Dark Elven Long Bow", category: "weapon", grade: "C", type: "bow" },
    { id: 110, name: "Halberd", category: "weapon", grade: "C", type: "spear" },
    { id: 111, name: "Partizan", category: "weapon", grade: "C", type: "spear" },
    { id: 112, name: "Scorpion", category: "weapon", grade: "C", type: "dagger" },
    { id: 113, name: "Deadman's Glory", category: "weapon", grade: "C", type: "dagger" },
    { id: 114, name: "Yaksa Mace", category: "weapon", grade: "C", type: "blunt" },
    { id: 115, name: "Bow of Peril", category: "weapon", grade: "C", type: "bow" },
    { id: 116, name: "Wizard's Tear", category: "weapon", grade: "C", type: "magic" },
    { id: 117, name: "Ecliptic Sword", category: "weapon", grade: "B", type: "sword" },
    { id: 118, name: "Crystal Dagger", category: "weapon", grade: "B", type: "dagger" },
    { id: 119, name: "Crystal Staff", category: "weapon", grade: "B", type: "magic" },
    { id: 120, name: "Sirra's Blade", category: "weapon", grade: "B", type: "sword" },
    { id: 121, name: "Dark Legion's Edge", category: "weapon", grade: "B", type: "two_sword" },
    { id: 122, name: "Berserker Blade", category: "weapon", grade: "B", type: "two_sword" },
    { id: 123, name: "Lance", category: "weapon", grade: "B", type: "spear" },
    { id: 124, name: "Shyeed's Bow", category: "weapon", grade: "B", type: "bow" },
    { id: 125, name: "Branch of the Mother Tree", category: "weapon", grade: "B", type: "magic" },
    { id: 126, name: "Wirframe Staff", category: "weapon", grade: "B", type: "magic" },
    { id: 127, name: "Doom Crusher", category: "weapon", grade: "B", type: "blunt" },
    { id: 128, name: "Naga Storm", category: "weapon", grade: "B", type: "blunt" },
    { id: 129, name: "Kris", category: "weapon", grade: "B", type: "dagger" },
    { id: 130, name: "Bloody Orchid", category: "weapon", grade: "B", type: "dagger" },
    { id: 131, name: "Zubei's Sword", category: "weapon", grade: "B", type: "sword" },
    { id: 132, name: "Akat Long Bow", category: "weapon", grade: "B", type: "bow" },
    { id: 133, name: "Cursed Maingauche", category: "weapon", grade: "A", type: "dagger" },
    { id: 134, name: "Sword of Ipos", category: "weapon", grade: "A", type: "sword" },
    { id: 135, name: "Basalt Battlehammer", category: "weapon", grade: "A", type: "blunt" },
    { id: 136, name: "Tallum Blade", category: "weapon", grade: "A", type: "dagger" },
    { id: 137, name: "Deadly Dagger", category: "weapon", grade: "A", type: "dagger" },
    { id: 138, name: "Majestic Sword", category: "weapon", grade: "A", type: "sword" },
    { id: 139, name: "Dual Majestic Sword", category: "weapon", grade: "A", type: "dual" },
    { id: 140, name: "Soul Separator", category: "weapon", grade: "A", type: "blunt" },
    { id: 141, name: "Shining Bow", category: "weapon", grade: "A", type: "bow" },
    { id: 142, name: "Demon Splinter", category: "weapon", grade: "A", type: "fist" },
    { id: 143, name: "Meteor Shower", category: "weapon", grade: "A", type: "magic" },
    { id: 144, name: "Dynasty Sword", category: "weapon", grade: "A", type: "sword" },
    { id: 145, name: "Dynasty Blade", category: "weapon", grade: "A", type: "dagger" },
    { id: 146, name: "Dynasty Crusher", category: "weapon", grade: "A", type: "blunt" },
    { id: 147, name: "Dynasty Bow", category: "weapon", grade: "A", type: "bow" },
    { id: 148, name: "Dynasty Staff", category: "weapon", grade: "A", type: "magic" },
    { id: 149, name: "Forgotten Blade", category: "weapon", grade: "S", type: "sword" },
    { id: 150, name: "Heaven's Divider", category: "weapon", grade: "S", type: "two_sword" },
    { id: 151, name: "Arcana Mace", category: "weapon", grade: "S", type: "blunt" },
    { id: 152, name: "Draconic Bow", category: "weapon", grade: "S", type: "bow" },
    { id: 153, name: "Demon Dagger", category: "weapon", grade: "S", type: "dagger" },
    { id: 154, name: "Raphael's Roar", category: "weapon", grade: "S", type: "blunt" },
    { id: 155, name: "Zariche", category: "weapon", grade: "S", type: "sword" },
    { id: 156, name: "Akamanah", category: "weapon", grade: "S", type: "dagger" },
    { id: 157, name: "Dual Forgotten Blade", category: "weapon", grade: "S", type: "dual" },
    { id: 158, name: "Dual Angel Slayer", category: "weapon", grade: "S", type: "dual" },
    { id: 159, name: "Icarus Spitter", category: "weapon", grade: "S", type: "bow" },
    { id: 160, name: "Icarus Hall", category: "weapon", grade: "S", type: "magic" },
    { id: 161, name: "Icarus Disperser", category: "weapon", grade: "S", type: "magic" },
    { id: 162, name: "Angel Slayer", category: "weapon", grade: "S", type: "dagger" },
    { id: 163, name: "Sirra's Blade (S)", category: "weapon", grade: "S", type: "sword" },
    { id: 164, name: "Vesper Noble Sword", category: "weapon", grade: "S80", type: "sword" },
    { id: 165, name: "Vesper Retributer", category: "weapon", grade: "S80", type: "blunt" },
    { id: 166, name: "Vesper Bow", category: "weapon", grade: "S80", type: "bow" },
    { id: 167, name: "Vesper Shaper", category: "weapon", grade: "S80", type: "dagger" },
    { id: 168, name: "Vesper Fighter", category: "weapon", grade: "S80", type: "fist" },
    { id: 169, name: "Vesper Caster", category: "weapon", grade: "S80", type: "magic" },
    { id: 170, name: "Vesper Singer", category: "weapon", grade: "S80", type: "magic" },
    { id: 171, name: "Vorpal Sword", category: "weapon", grade: "S84", type: "sword" },
    { id: 172, name: "Vorpal Blader", category: "weapon", grade: "S84", type: "dagger" },
    { id: 173, name: "Vorpal Retributer", category: "weapon", grade: "S84", type: "blunt" },
    { id: 174, name: "Vorpal Bow", category: "weapon", grade: "S84", type: "bow" },
    { id: 175, name: "Vorpal Caster", category: "weapon", grade: "S84", type: "magic" },
    { id: 176, name: "Dynasty Two-Handed Sword", category: "weapon", grade: "A", type: "two_sword" },
    { id: 177, name: "Haste Axe", category: "weapon", grade: "C", type: "blunt" },

    // ── ARMADURAS — Pesadas ───────────────────────────────────
    { id: 300, name: "Full Plate Armor", category: "armor", grade: "D", type: "heavy" },
    { id: 301, name: "Zubei's Armor", category: "armor", grade: "B", type: "heavy" },
    { id: 302, name: "Zubei's Breastplate", category: "armor", grade: "B", type: "heavy" },
    { id: 303, name: "Zubei's Gaiters", category: "armor", grade: "B", type: "heavy" },
    { id: 304, name: "Zubei's Helmet", category: "armor", grade: "B", type: "heavy" },
    { id: 305, name: "Zubei's Shield", category: "armor", grade: "B", type: "shield" },
    { id: 306, name: "Zubei's Gauntlets", category: "armor", grade: "B", type: "gloves" },
    { id: 307, name: "Zubei's Boots", category: "armor", grade: "B", type: "boots" },
    { id: 308, name: "Doom Plate Armor", category: "armor", grade: "B", type: "heavy" },
    { id: 309, name: "Doom Breastplate", category: "armor", grade: "B", type: "heavy" },
    { id: 310, name: "Doom Gaiters", category: "armor", grade: "B", type: "heavy" },
    { id: 311, name: "Doom Helmet", category: "armor", grade: "B", type: "heavy" },
    { id: 312, name: "Doom Shield", category: "armor", grade: "B", type: "shield" },
    { id: 313, name: "Doom Gloves", category: "armor", grade: "B", type: "gloves" },
    { id: 314, name: "Doom Boots", category: "armor", grade: "B", type: "boots" },
    { id: 315, name: "Dark Crystal Armor", category: "armor", grade: "A", type: "heavy" },
    { id: 316, name: "Tallum Plate Armor", category: "armor", grade: "A", type: "heavy" },
    { id: 317, name: "Imperial Crusader Armor", category: "armor", grade: "S", type: "heavy" },
    { id: 318, name: "Imperial Crusader Breastplate", category: "armor", grade: "S", type: "heavy" },
    { id: 319, name: "Imperial Crusader Gaiters", category: "armor", grade: "S", type: "heavy" },
    { id: 320, name: "Imperial Crusader Helmet", category: "armor", grade: "S", type: "heavy" },
    { id: 321, name: "Imperial Crusader Shield", category: "armor", grade: "S", type: "shield" },
    { id: 322, name: "Imperial Crusader Gauntlets", category: "armor", grade: "S", type: "gloves" },
    { id: 323, name: "Imperial Crusader Boots", category: "armor", grade: "S", type: "boots" },
    { id: 324, name: "Vesper Armor", category: "armor", grade: "S80", type: "heavy" },
    { id: 325, name: "Vesper Shield", category: "armor", grade: "S80", type: "shield" },
    { id: 326, name: "Vorpal Armor", category: "armor", grade: "S84", type: "heavy" },

    // ── ARMADURAS — Ligeras ───────────────────────────────────
    { id: 350, name: "Devotion Armor", category: "armor", grade: "NG", type: "light" },
    { id: 351, name: "Devotion Leather Armor", category: "armor", grade: "NG", type: "light" },
    { id: 352, name: "Hasted Leather Armor", category: "armor", grade: "C", type: "light" },
    { id: 353, name: "String Leather Armor", category: "armor", grade: "C", type: "light" },
    { id: 354, name: "Blue Wolf Breastplate", category: "armor", grade: "B", type: "light" },
    { id: 355, name: "Blue Wolf Gaiters", category: "armor", grade: "B", type: "light" },
    { id: 356, name: "Blue Wolf Helmet", category: "armor", grade: "B", type: "light" },
    { id: 357, name: "Blue Wolf Gloves", category: "armor", grade: "B", type: "gloves" },
    { id: 358, name: "Blue Wolf Boots", category: "armor", grade: "B", type: "boots" },
    { id: 359, name: "Doom Leather Armor", category: "armor", grade: "B", type: "light" },
    { id: 360, name: "Dark Crystal Leather Armor", category: "armor", grade: "A", type: "light" },
    { id: 361, name: "Tallum Leather Armor", category: "armor", grade: "A", type: "light" },
    { id: 362, name: "Dynasty Leather Armor", category: "armor", grade: "A", type: "light" },
    { id: 363, name: "Draconic Leather Armor", category: "armor", grade: "S", type: "light" },
    { id: 364, name: "Draconic Leather Breastplate", category: "armor", grade: "S", type: "light" },
    { id: 365, name: "Draconic Leather Gaiters", category: "armor", grade: "S", type: "light" },
    { id: 366, name: "Draconic Leather Helmet", category: "armor", grade: "S", type: "light" },
    { id: 367, name: "Draconic Leather Gloves", category: "armor", grade: "S", type: "gloves" },
    { id: 368, name: "Draconic Leather Boots", category: "armor", grade: "S", type: "boots" },
    { id: 369, name: "Vesper Leather Armor", category: "armor", grade: "S80", type: "light" },
    { id: 370, name: "Vorpal Leather Armor", category: "armor", grade: "S84", type: "light" },

    // ── ARMADURAS — Mágicas ───────────────────────────────────
    { id: 400, name: "Robe of Magic", category: "armor", grade: "D", type: "robe" },
    { id: 401, name: "Blue Wolf Robe", category: "armor", grade: "B", type: "robe" },
    { id: 402, name: "Blue Wolf Robe Set", category: "armor", grade: "B", type: "robe" },
    { id: 403, name: "Doom Robe", category: "armor", grade: "B", type: "robe" },
    { id: 404, name: "Dark Crystal Robe", category: "armor", grade: "A", type: "robe" },
    { id: 405, name: "Tallum Robe", category: "armor", grade: "A", type: "robe" },
    { id: 406, name: "Majestic Robe", category: "armor", grade: "A", type: "robe" },
    { id: 407, name: "Dynasty Robe", category: "armor", grade: "A", type: "robe" },
    { id: 408, name: "Arcana Robe", category: "armor", grade: "S", type: "robe" },
    { id: 409, name: "Arcana Circlet", category: "armor", grade: "S", type: "robe" },
    { id: 410, name: "Arcana Gloves", category: "armor", grade: "S", type: "gloves" },
    { id: 411, name: "Arcana Boots", category: "armor", grade: "S", type: "boots" },
    { id: 412, name: "Vesper Robe", category: "armor", grade: "S80", type: "robe" },
    { id: 413, name: "Vorpal Robe", category: "armor", grade: "S84", type: "robe" },

    // ── JOYAS ─────────────────────────────────────────────────
    { id: 500, name: "Necklace of Devotion", category: "jewelry", grade: "NG", type: "necklace" },
    { id: 501, name: "Earring of Devotion", category: "jewelry", grade: "NG", type: "earring" },
    { id: 502, name: "Ring of Devotion", category: "jewelry", grade: "NG", type: "ring" },
    { id: 503, name: "Elbows Necklace", category: "jewelry", grade: "C", type: "necklace" },
    { id: 504, name: "Blue Wolf Necklace", category: "jewelry", grade: "B", type: "necklace" },
    { id: 505, name: "Blue Wolf Earrings", category: "jewelry", grade: "B", type: "earring" },
    { id: 506, name: "Blue Wolf Ring", category: "jewelry", grade: "B", type: "ring" },
    { id: 507, name: "Doom Necklace", category: "jewelry", grade: "B", type: "necklace" },
    { id: 508, name: "Doom Earrings", category: "jewelry", grade: "B", type: "earring" },
    { id: 509, name: "Doom Ring", category: "jewelry", grade: "B", type: "ring" },
    { id: 510, name: "Majestic Necklace", category: "jewelry", grade: "A", type: "necklace" },
    { id: 511, name: "Majestic Earrings", category: "jewelry", grade: "A", type: "earring" },
    { id: 512, name: "Majestic Ring", category: "jewelry", grade: "A", type: "ring" },
    { id: 513, name: "Tallum Necklace", category: "jewelry", grade: "A", type: "necklace" },
    { id: 514, name: "Tallum Earrings", category: "jewelry", grade: "A", type: "earring" },
    { id: 515, name: "Tallum Ring", category: "jewelry", grade: "A", type: "ring" },
    { id: 516, name: "Dynasty Necklace", category: "jewelry", grade: "A", type: "necklace" },
    { id: 517, name: "Dynasty Earrings", category: "jewelry", grade: "A", type: "earring" },
    { id: 518, name: "Dynasty Ring", category: "jewelry", grade: "A", type: "ring" },
    { id: 519, name: "Baium's Ring", category: "jewelry", grade: "S", type: "ring" },
    { id: 520, name: "Antharas' Earring", category: "jewelry", grade: "S", type: "earring" },
    { id: 521, name: "Valakas' Necklace", category: "jewelry", grade: "S", type: "necklace" },
    { id: 522, name: "Zaken's Earring", category: "jewelry", grade: "S", type: "earring" },
    { id: 523, name: "Queen Ant's Ring", category: "jewelry", grade: "A", type: "ring" },
    { id: 524, name: "Orfen's Earring", category: "jewelry", grade: "A", type: "earring" },
    { id: 525, name: "Core's Ring", category: "jewelry", grade: "A", type: "ring" },
    { id: 526, name: "Vesper Necklace", category: "jewelry", grade: "S80", type: "necklace" },
    { id: 527, name: "Vesper Earrings", category: "jewelry", grade: "S80", type: "earring" },
    { id: 528, name: "Vesper Ring", category: "jewelry", grade: "S80", type: "ring" },
    { id: 529, name: "Vorpal Ring", category: "jewelry", grade: "S84", type: "ring" },
    { id: 530, name: "Vorpal Earrings", category: "jewelry", grade: "S84", type: "earring" },
    { id: 531, name: "Vorpal Necklace", category: "jewelry", grade: "S84", type: "necklace" },
    { id: 532, name: "Lindvior's Earring", category: "jewelry", grade: "S84", type: "earring" },
    { id: 533, name: "Istina's Necklace", category: "jewelry", grade: "S84", type: "necklace" },
    { id: 534, name: "Octavis' Ring", category: "jewelry", grade: "S84", type: "ring" },
    { id: 535, name: "Sealed Tateossian Ring", category: "jewelry", grade: "S", type: "ring" },
    { id: 536, name: "Sealed Tateossian Earring", category: "jewelry", grade: "S", type: "earring" },
    { id: 537, name: "Sealed Tateossian Necklace", category: "jewelry", grade: "S", type: "necklace" },

    // ── MATERIALES ────────────────────────────────────────────
    { id: 700, name: "Iron Ore", category: "material", grade: "", type: "resource" },
    { id: 701, name: "Coal", category: "material", grade: "", type: "resource" },
    { id: 702, name: "Charcoal", category: "material", grade: "", type: "resource" },
    { id: 703, name: "Animal Skin", category: "material", grade: "", type: "resource" },
    { id: 704, name: "Animal Bone", category: "material", grade: "", type: "resource" },
    { id: 705, name: "Stem", category: "material", grade: "", type: "resource" },
    { id: 706, name: "Suede", category: "material", grade: "", type: "resource" },
    { id: 707, name: "Thread", category: "material", grade: "", type: "resource" },
    { id: 708, name: "Varnish", category: "material", grade: "", type: "resource" },
    { id: 709, name: "Silver Nugget", category: "material", grade: "", type: "resource" },
    { id: 710, name: "Synthetic Cokes", category: "material", grade: "", type: "resource" },
    { id: 711, name: "Mithril Ore", category: "material", grade: "", type: "resource" },
    { id: 712, name: "Adamantite Nugget", category: "material", grade: "", type: "resource" },
    { id: 713, name: "Oriharukon Ore", category: "material", grade: "", type: "resource" },
    { id: 714, name: "Mold Glue", category: "material", grade: "", type: "resource" },
    { id: 715, name: "Mold Lubricant", category: "material", grade: "", type: "resource" },
    { id: 716, name: "Mold Hardener", category: "material", grade: "", type: "resource" },
    { id: 717, name: "Asofe", category: "material", grade: "", type: "key_material" },
    { id: 718, name: "Enria", category: "material", grade: "", type: "key_material" },
    { id: 719, name: "Thons", category: "material", grade: "", type: "key_material" },
    { id: 720, name: "Stone of Purity", category: "material", grade: "", type: "key_material" },
    { id: 721, name: "Crystal D-Grade", category: "material", grade: "D", type: "crystal" },
    { id: 722, name: "Crystal C-Grade", category: "material", grade: "C", type: "crystal" },
    { id: 723, name: "Crystal B-Grade", category: "material", grade: "B", type: "crystal" },
    { id: 724, name: "Crystal A-Grade", category: "material", grade: "A", type: "crystal" },
    { id: 725, name: "Crystal S-Grade", category: "material", grade: "S", type: "crystal" },
    { id: 726, name: "Lesser Giant's Codex", category: "material", grade: "", type: "spellbook" },
    { id: 727, name: "Giant's Codex", category: "material", grade: "", type: "spellbook" },
    { id: 728, name: "Giant's Codex - Mastery", category: "material", grade: "", type: "spellbook" },
    { id: 729, name: "Gemstone D", category: "material", grade: "D", type: "gemstone" },
    { id: 730, name: "Gemstone C", category: "material", grade: "C", type: "gemstone" },
    { id: 731, name: "Gemstone B", category: "material", grade: "B", type: "gemstone" },
    { id: 732, name: "Gemstone A", category: "material", grade: "A", type: "gemstone" },
    { id: 733, name: "Gemstone S", category: "material", grade: "S", type: "gemstone" },
    { id: 734, name: "Sealed Rune", category: "material", grade: "", type: "resource" },
    { id: 735, name: "Cloth Piece", category: "material", grade: "", type: "resource" },
    { id: 736, name: "Leather", category: "material", grade: "", type: "resource" },
    { id: 737, name: "Cobweb", category: "material", grade: "", type: "resource" },
    { id: 738, name: "Dye Powder", category: "material", grade: "", type: "resource" },
    { id: 739, name: "Oriharukon", category: "material", grade: "", type: "resource" },
    { id: 740, name: "Braided Hemp", category: "material", grade: "", type: "resource" },
    { id: 741, name: "Sealed Tateossian Ring Gem", category: "material", grade: "S", type: "key_material" },
    { id: 742, name: "Sealed Tateossian Earring Part", category: "material", grade: "S", type: "key_material" },
    { id: 743, name: "Sealed Tateossian Necklace Chain", category: "material", grade: "S", type: "key_material" },

    // ── RECETAS ───────────────────────────────────────────────
    { id: 800, name: "Recipe: Draconic Bow", category: "recipe", grade: "S", type: "weapon_recipe" },
    { id: 801, name: "Recipe: Forgotten Blade", category: "recipe", grade: "S", type: "weapon_recipe" },
    { id: 802, name: "Recipe: Heaven's Divider", category: "recipe", grade: "S", type: "weapon_recipe" },
    { id: 803, name: "Recipe: Angel Slayer", category: "recipe", grade: "S", type: "weapon_recipe" },
    { id: 804, name: "Recipe: Arcana Mace", category: "recipe", grade: "S", type: "weapon_recipe" },
    { id: 805, name: "Recipe: Imperial Crusader", category: "recipe", grade: "S", type: "armor_recipe" },
    { id: 806, name: "Recipe: Draconic Leather", category: "recipe", grade: "S", type: "armor_recipe" },
    { id: 807, name: "Recipe: Arcana Robe", category: "recipe", grade: "S", type: "armor_recipe" },
    { id: 808, name: "Recipe: Majestic Sword", category: "recipe", grade: "A", type: "weapon_recipe" },
    { id: 809, name: "Recipe: Vesper Sword", category: "recipe", grade: "S80", type: "weapon_recipe" },
    { id: 810, name: "Recipe: Soulshot S", category: "recipe", grade: "S", type: "shot_recipe" },
    { id: 811, name: "Recipe: Blessed Spiritshot S", category: "recipe", grade: "S", type: "shot_recipe" },
    { id: 812, name: "Recipe: Soulshot A", category: "recipe", grade: "A", type: "shot_recipe" },
    { id: 813, name: "Recipe: Soulshot B", category: "recipe", grade: "B", type: "shot_recipe" },
    { id: 814, name: "Recipe: Sealed Tateossian Ring (70%)", category: "recipe", grade: "S", type: "jewelry_recipe" },
    { id: 815, name: "Recipe: Sealed Tateossian Earring (70%)", category: "recipe", grade: "S", type: "jewelry_recipe" },
    { id: 816, name: "Recipe: Sealed Tateossian Necklace (70%)", category: "recipe", grade: "S", type: "jewelry_recipe" },

    // ── CONSUMIBLES ───────────────────────────────────────────
    { id: 900, name: "Soulshot D-Grade", category: "consumable", grade: "D", type: "shot" },
    { id: 901, name: "Soulshot C-Grade", category: "consumable", grade: "C", type: "shot" },
    { id: 902, name: "Soulshot B-Grade", category: "consumable", grade: "B", type: "shot" },
    { id: 903, name: "Soulshot A-Grade", category: "consumable", grade: "A", type: "shot" },
    { id: 904, name: "Soulshot S-Grade", category: "consumable", grade: "S", type: "shot" },
    { id: 905, name: "Spiritshot D-Grade", category: "consumable", grade: "D", type: "shot" },
    { id: 906, name: "Spiritshot C-Grade", category: "consumable", grade: "C", type: "shot" },
    { id: 907, name: "Spiritshot B-Grade", category: "consumable", grade: "B", type: "shot" },
    { id: 908, name: "Spiritshot A-Grade", category: "consumable", grade: "A", type: "shot" },
    { id: 909, name: "Spiritshot S-Grade", category: "consumable", grade: "S", type: "shot" },
    { id: 910, name: "Blessed Spiritshot D", category: "consumable", grade: "D", type: "shot" },
    { id: 911, name: "Blessed Spiritshot C", category: "consumable", grade: "C", type: "shot" },
    { id: 912, name: "Blessed Spiritshot B", category: "consumable", grade: "B", type: "shot" },
    { id: 913, name: "Blessed Spiritshot A", category: "consumable", grade: "A", type: "shot" },
    { id: 914, name: "Blessed Spiritshot S", category: "consumable", grade: "S", type: "shot" },
    { id: 915, name: "CP Potion", category: "consumable", grade: "", type: "potion" },
    { id: 916, name: "Greater CP Potion", category: "consumable", grade: "", type: "potion" },
    { id: 917, name: "HP Potion", category: "consumable", grade: "", type: "potion" },
    { id: 918, name: "Greater HP Potion", category: "consumable", grade: "", type: "potion" },
    { id: 919, name: "MP Potion", category: "consumable", grade: "", type: "potion" },
    { id: 920, name: "Greater MP Potion", category: "consumable", grade: "", type: "potion" },
    { id: 921, name: "Haste Potion", category: "consumable", grade: "", type: "potion" },
    { id: 922, name: "Quick Healing Potion", category: "consumable", grade: "", type: "potion" },
    { id: 923, name: "Elixir of CP (A)", category: "consumable", grade: "A", type: "elixir" },
    { id: 924, name: "Elixir of CP (S)", category: "consumable", grade: "S", type: "elixir" },
    { id: 925, name: "Scroll of Escape", category: "consumable", grade: "", type: "scroll" },
    { id: 926, name: "Scroll of Resurrection", category: "consumable", grade: "", type: "scroll" },
    { id: 927, name: "Scroll of Resurrection (Pet)", category: "consumable", grade: "", type: "scroll" },

    // ── SCROLLS DE ENCANTAMIENTO ───────────────────────────────
    { id: 950, name: "Scroll: Enchant Weapon D", category: "scroll", grade: "D", type: "enchant" },
    { id: 951, name: "Scroll: Enchant Weapon C", category: "scroll", grade: "C", type: "enchant" },
    { id: 952, name: "Scroll: Enchant Weapon B", category: "scroll", grade: "B", type: "enchant" },
    { id: 953, name: "Scroll: Enchant Weapon A", category: "scroll", grade: "A", type: "enchant" },
    { id: 954, name: "Scroll: Enchant Weapon S", category: "scroll", grade: "S", type: "enchant" },
    { id: 955, name: "Scroll: Enchant Armor D", category: "scroll", grade: "D", type: "enchant" },
    { id: 956, name: "Scroll: Enchant Armor C", category: "scroll", grade: "C", type: "enchant" },
    { id: 957, name: "Scroll: Enchant Armor B", category: "scroll", grade: "B", type: "enchant" },
    { id: 958, name: "Scroll: Enchant Armor A", category: "scroll", grade: "A", type: "enchant" },
    { id: 959, name: "Scroll: Enchant Armor S", category: "scroll", grade: "S", type: "enchant" },
    { id: 960, name: "Blessed Scroll: Enchant Weapon S", category: "scroll", grade: "S", type: "enchant" },
    { id: 961, name: "Blessed Scroll: Enchant Armor S", category: "scroll", grade: "S", type: "enchant" },
    { id: 962, name: "Blessed Scroll: Enchant Weapon A", category: "scroll", grade: "A", type: "enchant" },
    { id: 963, name: "Blessed Scroll: Enchant Armor A", category: "scroll", grade: "A", type: "enchant" },
    { id: 964, name: "Ancient Book: Divine Inspiration", category: "scroll", grade: "", type: "skill_book" },

    // ── ITEMS ESPECIALES / BOSS DROPS ─────────────────────────
    { id: 1000, name: "Life Stone (Lv.46)", category: "special", grade: "", type: "life_stone" },
    { id: 1001, name: "Life Stone (Lv.52)", category: "special", grade: "", type: "life_stone" },
    { id: 1002, name: "Life Stone (Lv.55)", category: "special", grade: "", type: "life_stone" },
    { id: 1003, name: "Life Stone (Lv.58)", category: "special", grade: "", type: "life_stone" },
    { id: 1004, name: "Life Stone (Lv.61)", category: "special", grade: "", type: "life_stone" },
    { id: 1005, name: "Life Stone (Lv.64)", category: "special", grade: "", type: "life_stone" },
    { id: 1006, name: "Life Stone (Lv.67)", category: "special", grade: "", type: "life_stone" },
    { id: 1007, name: "Life Stone (Lv.70)", category: "special", grade: "", type: "life_stone" },
    { id: 1008, name: "Life Stone (Lv.76)", category: "special", grade: "", type: "life_stone" },
    { id: 1009, name: "Mid-grade Life Stone (Lv.76)", category: "special", grade: "", type: "life_stone" },
    { id: 1010, name: "High-grade Life Stone (Lv.76)", category: "special", grade: "", type: "life_stone" },
    { id: 1011, name: "Top-grade Life Stone (Lv.76)", category: "special", grade: "", type: "life_stone" },
    { id: 1012, name: "Soul Crystal (Lv.1)", category: "special", grade: "", type: "soul_crystal" },
    { id: 1013, name: "Soul Crystal (Lv.5)", category: "special", grade: "", type: "soul_crystal" },
    { id: 1014, name: "Soul Crystal (Lv.10)", category: "special", grade: "", type: "soul_crystal" },
    { id: 1015, name: "Soul Crystal (Lv.13)", category: "special", grade: "", type: "soul_crystal" },
    { id: 1016, name: "Soul Crystal (Lv.15)", category: "special", grade: "", type: "soul_crystal" },
    { id: 1017, name: "Spellbook: Feather of Death", category: "special", grade: "", type: "spellbook" },
    { id: 1018, name: "Spellbook: Meteor Storm", category: "special", grade: "", type: "spellbook" },
    { id: 1019, name: "Spellbook: Corpse Burst", category: "special", grade: "", type: "spellbook" },
    { id: 1020, name: "Spellbook: Warp", category: "special", grade: "", type: "spellbook" },
    { id: 1021, name: "Event Medal", category: "special", grade: "", type: "event" },
    { id: 1022, name: "Clan Reputation Score", category: "special", grade: "", type: "clan" },
    { id: 1023, name: "Attribute Pouch", category: "special", grade: "", type: "event" },
    { id: 1024, name: "R-grade Scroll", category: "special", grade: "", type: "scroll" },
    { id: 1025, name: "Hero Weapon Exchange Coupon", category: "special", grade: "", type: "hero" },
    { id: 1026, name: "Talisman of Eva", category: "special", grade: "", type: "talisman" },
    { id: 1027, name: "Talisman of Baium", category: "special", grade: "", type: "talisman" },
    { id: 1028, name: "Talisman of Antharas", category: "special", grade: "", type: "talisman" },
    { id: 1029, name: "Olympiad Token", category: "special", grade: "", type: "olympiad" },
    { id: 1030, name: "Strider", category: "special", grade: "", type: "pet" },
    { id: 1031, name: "Great Magic Wolf", category: "special", grade: "", type: "pet" },
    { id: 1032, name: "Buffalo", category: "special", grade: "", type: "pet" },
    { id: 1033, name: "Improved Kat the Cat", category: "special", grade: "", type: "pet" },
    // ══ ARMADURAS PESADAS — Sets completos que faltaban ══════

    // Dark Crystal Heavy (A)
    { id: 2100, name: "Dark Crystal Breastplate", category: "armor", grade: "A", type: "heavy" },
    { id: 2101, name: "Dark Crystal Gaiters", category: "armor", grade: "A", type: "heavy" },
    { id: 2102, name: "Dark Crystal Helmet", category: "armor", grade: "A", type: "heavy" },
    { id: 2103, name: "Dark Crystal Shield", category: "armor", grade: "A", type: "shield" },
    { id: 2104, name: "Dark Crystal Gloves", category: "armor", grade: "A", type: "gloves" },
    { id: 2105, name: "Dark Crystal Boots", category: "armor", grade: "A", type: "boots" },

    // Tallum Heavy (A)
    { id: 2110, name: "Tallum Plate Breastplate", category: "armor", grade: "A", type: "heavy" },
    { id: 2111, name: "Tallum Plate Gaiters", category: "armor", grade: "A", type: "heavy" },
    { id: 2112, name: "Tallum Plate Helmet", category: "armor", grade: "A", type: "heavy" },
    { id: 2113, name: "Tallum Plate Shield", category: "armor", grade: "A", type: "shield" },
    { id: 2114, name: "Tallum Plate Gloves", category: "armor", grade: "A", type: "gloves" },
    { id: 2115, name: "Tallum Plate Boots", category: "armor", grade: "A", type: "boots" },

    // Majestic Heavy (A)
    { id: 2120, name: "Majestic Plate Armor", category: "armor", grade: "A", type: "heavy" },
    { id: 2121, name: "Majestic Plate Breastplate", category: "armor", grade: "A", type: "heavy" },
    { id: 2122, name: "Majestic Plate Gaiters", category: "armor", grade: "A", type: "heavy" },
    { id: 2123, name: "Majestic Plate Helmet", category: "armor", grade: "A", type: "heavy" },
    { id: 2124, name: "Majestic Shield", category: "armor", grade: "A", type: "shield" },
    { id: 2125, name: "Majestic Gauntlets", category: "armor", grade: "A", type: "gloves" },
    { id: 2126, name: "Majestic Boots", category: "armor", grade: "A", type: "boots" },

    // Dynasty Heavy (A)
    { id: 2130, name: "Dynasty Plate Armor", category: "armor", grade: "A", type: "heavy" },
    { id: 2131, name: "Dynasty Breastplate", category: "armor", grade: "A", type: "heavy" },
    { id: 2132, name: "Dynasty Gaiters", category: "armor", grade: "A", type: "heavy" },
    { id: 2133, name: "Dynasty Helmet", category: "armor", grade: "A", type: "heavy" },
    { id: 2134, name: "Dynasty Shield", category: "armor", grade: "A", type: "shield" },
    { id: 2135, name: "Dynasty Gloves", category: "armor", grade: "A", type: "gloves" },
    { id: 2136, name: "Dynasty Boots", category: "armor", grade: "A", type: "boots" },

    // Imperial Crusader (S) — piezas adicionales
    { id: 2140, name: "Imperial Crusader Armor (Full)", category: "armor", grade: "S", type: "heavy" },

    // Vesper Heavy (S80) — set completo
    { id: 2150, name: "Vesper Breastplate", category: "armor", grade: "S80", type: "heavy" },
    { id: 2151, name: "Vesper Gaiters", category: "armor", grade: "S80", type: "heavy" },
    { id: 2152, name: "Vesper Helmet", category: "armor", grade: "S80", type: "heavy" },
    { id: 2153, name: "Vesper Gauntlets", category: "armor", grade: "S80", type: "gloves" },
    { id: 2154, name: "Vesper Boots", category: "armor", grade: "S80", type: "boots" },

    // Vorpal Heavy (S84) — set completo
    { id: 2160, name: "Vorpal Breastplate", category: "armor", grade: "S84", type: "heavy" },
    { id: 2161, name: "Vorpal Gaiters", category: "armor", grade: "S84", type: "heavy" },
    { id: 2162, name: "Vorpal Helmet", category: "armor", grade: "S84", type: "heavy" },
    { id: 2163, name: "Vorpal Shield", category: "armor", grade: "S84", type: "shield" },
    { id: 2164, name: "Vorpal Gauntlets", category: "armor", grade: "S84", type: "gloves" },
    { id: 2165, name: "Vorpal Boots", category: "armor", grade: "S84", type: "boots" },

    // ══ ARMADURAS LIGERAS — Sets completos ══════════════════

    // Dark Crystal Light (A)
    { id: 2200, name: "Dark Crystal Leather Armor", category: "armor", grade: "A", type: "light" },
    { id: 2201, name: "Dark Crystal Leather Breastplate", category: "armor", grade: "A", type: "light" },
    { id: 2202, name: "Dark Crystal Leather Gaiters", category: "armor", grade: "A", type: "light" },
    { id: 2203, name: "Dark Crystal Leather Helmet", category: "armor", grade: "A", type: "light" },
    { id: 2204, name: "Dark Crystal Leather Gloves", category: "armor", grade: "A", type: "gloves" },
    { id: 2205, name: "Dark Crystal Leather Boots", category: "armor", grade: "A", type: "boots" },

    // Majestic Leather (A)
    { id: 2210, name: "Majestic Leather Armor", category: "armor", grade: "A", type: "light" },
    { id: 2211, name: "Majestic Leather Breastplate", category: "armor", grade: "A", type: "light" },
    { id: 2212, name: "Majestic Leather Gaiters", category: "armor", grade: "A", type: "light" },
    { id: 2213, name: "Majestic Leather Helmet", category: "armor", grade: "A", type: "light" },
    { id: 2214, name: "Majestic Leather Gloves", category: "armor", grade: "A", type: "gloves" },
    { id: 2215, name: "Majestic Leather Boots", category: "armor", grade: "A", type: "boots" },

    // Vesper Leather (S80)
    { id: 2220, name: "Vesper Leather Breastplate", category: "armor", grade: "S80", type: "light" },
    { id: 2221, name: "Vesper Leather Gaiters", category: "armor", grade: "S80", type: "light" },
    { id: 2222, name: "Vesper Leather Helmet", category: "armor", grade: "S80", type: "light" },
    { id: 2223, name: "Vesper Leather Gloves", category: "armor", grade: "S80", type: "gloves" },
    { id: 2224, name: "Vesper Leather Boots", category: "armor", grade: "S80", type: "boots" },

    // Vorpal Leather (S84)
    { id: 2230, name: "Vorpal Leather Breastplate", category: "armor", grade: "S84", type: "light" },
    { id: 2231, name: "Vorpal Leather Gaiters", category: "armor", grade: "S84", type: "light" },
    { id: 2232, name: "Vorpal Leather Helmet", category: "armor", grade: "S84", type: "light" },
    { id: 2233, name: "Vorpal Leather Gloves", category: "armor", grade: "S84", type: "gloves" },
    { id: 2234, name: "Vorpal Leather Boots", category: "armor", grade: "S84", type: "boots" },

    // ══ ARMADURAS MÁGICAS — Sets completos ══════════════════

    // Dark Crystal Robe (A)
    { id: 2300, name: "Dark Crystal Robe", category: "armor", grade: "A", type: "robe" },
    { id: 2301, name: "Dark Crystal Circlet", category: "armor", grade: "A", type: "robe" },
    { id: 2302, name: "Dark Crystal Gloves", category: "armor", grade: "A", type: "gloves" },
    { id: 2303, name: "Dark Crystal Boots", category: "armor", grade: "A", type: "boots" },

    // Tallum Robe (A)
    { id: 2310, name: "Tallum Robe", category: "armor", grade: "A", type: "robe" },
    { id: 2311, name: "Tallum Dark Cloak", category: "armor", grade: "A", type: "robe" },
    { id: 2312, name: "Tallum Circlet", category: "armor", grade: "A", type: "robe" },
    { id: 2313, name: "Tallum Gloves", category: "armor", grade: "A", type: "gloves" },
    { id: 2314, name: "Tallum Boots", category: "armor", grade: "A", type: "boots" },

    // Majestic Robe (A)
    { id: 2320, name: "Majestic Robe", category: "armor", grade: "A", type: "robe" },
    { id: 2321, name: "Majestic Circlet", category: "armor", grade: "A", type: "robe" },
    { id: 2322, name: "Majestic Gloves", category: "armor", grade: "A", type: "gloves" },
    { id: 2323, name: "Majestic Boots", category: "armor", grade: "A", type: "boots" },

    // Dynasty Robe (A)
    { id: 2330, name: "Dynasty Robe", category: "armor", grade: "A", type: "robe" },
    { id: 2331, name: "Dynasty Circlet", category: "armor", grade: "A", type: "robe" },
    { id: 2332, name: "Dynasty Gloves", category: "armor", grade: "A", type: "gloves" },
    { id: 2333, name: "Dynasty Boots", category: "armor", grade: "A", type: "boots" },

    // Arcana (S) — set completo
    { id: 2340, name: "Arcana Robe Set", category: "armor", grade: "S", type: "robe" },

    // Vesper Robe (S80)
    { id: 2350, name: "Vesper Circlet", category: "armor", grade: "S80", type: "robe" },
    { id: 2351, name: "Vesper Gloves", category: "armor", grade: "S80", type: "gloves" },
    { id: 2352, name: "Vesper Boots", category: "armor", grade: "S80", type: "boots" },

    // Vorpal Robe (S84)
    { id: 2360, name: "Vorpal Circlet", category: "armor", grade: "S84", type: "robe" },
    { id: 2361, name: "Vorpal Robe Gloves", category: "armor", grade: "S84", type: "gloves" },
    { id: 2362, name: "Vorpal Robe Boots", category: "armor", grade: "S84", type: "boots" },

    // ══ SETS GRADO C — Completos ════════════════════════════
    { id: 2400, name: "Avadon Armor", category: "armor", grade: "C", type: "heavy" },
    { id: 2401, name: "Avadon Breastplate", category: "armor", grade: "C", type: "heavy" },
    { id: 2402, name: "Avadon Gaiters", category: "armor", grade: "C", type: "heavy" },
    { id: 2403, name: "Avadon Helmet", category: "armor", grade: "C", type: "heavy" },
    { id: 2404, name: "Avadon Shield", category: "armor", grade: "C", type: "shield" },
    { id: 2405, name: "Avadon Gloves", category: "armor", grade: "C", type: "gloves" },
    { id: 2406, name: "Avadon Boots", category: "armor", grade: "C", type: "boots" },
    { id: 2410, name: "Avadon Leather Armor", category: "armor", grade: "C", type: "light" },
    { id: 2411, name: "Avadon Leather Gaiters", category: "armor", grade: "C", type: "light" },
    { id: 2412, name: "Avadon Leather Helmet", category: "armor", grade: "C", type: "light" },
    { id: 2413, name: "Avadon Leather Gloves", category: "armor", grade: "C", type: "gloves" },
    { id: 2414, name: "Avadon Leather Boots", category: "armor", grade: "C", type: "boots" },
    { id: 2420, name: "Avadon Robe", category: "armor", grade: "C", type: "robe" },
    { id: 2421, name: "Avadon Circlet", category: "armor", grade: "C", type: "robe" },
    { id: 2422, name: "Avadon Robe Gloves", category: "armor", grade: "C", type: "gloves" },
    { id: 2423, name: "Avadon Robe Boots", category: "armor", grade: "C", type: "boots" },

    // ══ JOYAS — Sets completos por grado ════════════════════

    // Grado D
    { id: 2500, name: "Necklace of Anguish", category: "jewelry", grade: "D", type: "necklace" },
    { id: 2501, name: "Earring of Anguish", category: "jewelry", grade: "D", type: "earring" },
    { id: 2502, name: "Ring of Anguish", category: "jewelry", grade: "D", type: "ring" },
    { id: 2503, name: "Necklace of Mermaid", category: "jewelry", grade: "D", type: "necklace" },
    { id: 2504, name: "Earring of Mermaid", category: "jewelry", grade: "D", type: "earring" },
    { id: 2505, name: "Ring of Mermaid", category: "jewelry", grade: "D", type: "ring" },

    // Grado C
    { id: 2510, name: "Necklace of Avadon", category: "jewelry", grade: "C", type: "necklace" },
    { id: 2511, name: "Earring of Avadon", category: "jewelry", grade: "C", type: "earring" },
    { id: 2512, name: "Ring of Avadon", category: "jewelry", grade: "C", type: "ring" },
    { id: 2513, name: "Necklace of Black Ore", category: "jewelry", grade: "C", type: "necklace" },
    { id: 2514, name: "Earring of Black Ore", category: "jewelry", grade: "C", type: "earring" },
    { id: 2515, name: "Ring of Black Ore", category: "jewelry", grade: "C", type: "ring" },

    // Grado B completo
    { id: 2520, name: "Necklace of Zubei", category: "jewelry", grade: "B", type: "necklace" },
    { id: 2521, name: "Earring of Zubei", category: "jewelry", grade: "B", type: "earring" },
    { id: 2522, name: "Ring of Zubei", category: "jewelry", grade: "B", type: "ring" },
    { id: 2523, name: "Necklace of Darkness", category: "jewelry", grade: "B", type: "necklace" },
    { id: 2524, name: "Earring of Darkness", category: "jewelry", grade: "B", type: "earring" },
    { id: 2525, name: "Ring of Darkness", category: "jewelry", grade: "B", type: "ring" },
    { id: 2526, name: "Necklace of Protection", category: "jewelry", grade: "B", type: "necklace" },
    { id: 2527, name: "Earring of Protection", category: "jewelry", grade: "B", type: "earring" },
    { id: 2528, name: "Ring of Protection", category: "jewelry", grade: "B", type: "ring" },

    // Grado A adicional
    { id: 2530, name: "Dark Crystal Necklace", category: "jewelry", grade: "A", type: "necklace" },
    { id: 2531, name: "Dark Crystal Earrings", category: "jewelry", grade: "A", type: "earring" },
    { id: 2532, name: "Dark Crystal Ring", category: "jewelry", grade: "A", type: "ring" },
    { id: 2533, name: "Necklace of Reckoning", category: "jewelry", grade: "A", type: "necklace" },
    { id: 2534, name: "Earring of Reckoning", category: "jewelry", grade: "A", type: "earring" },
    { id: 2535, name: "Ring of Reckoning", category: "jewelry", grade: "A", type: "ring" },

    // Grado S — Joyas adicionales
    { id: 2540, name: "Icarus Ring", category: "jewelry", grade: "S", type: "ring" },
    { id: 2541, name: "Icarus Earring", category: "jewelry", grade: "S", type: "earring" },
    { id: 2542, name: "Icarus Necklace", category: "jewelry", grade: "S", type: "necklace" },
    { id: 2543, name: "Necklace of the Dwarf King", category: "jewelry", grade: "S", type: "necklace" },
    { id: 2544, name: "Earring of the Dwarf King", category: "jewelry", grade: "S", type: "earring" },
    { id: 2545, name: "Ring of the Dwarf King", category: "jewelry", grade: "S", type: "ring" },
    { id: 2546, name: "Frintezza's Necklace", category: "jewelry", grade: "S", type: "necklace" },

    // ══ ARMAS ADICIONALES — Grado B ═════════════════════════
    { id: 2600, name: "Bow of Anguish", category: "weapon", grade: "B", type: "bow" },
    { id: 2601, name: "Elven Bow", category: "weapon", grade: "B", type: "bow" },
    { id: 2602, name: "Demon Staff", category: "weapon", grade: "B", type: "magic" },
    { id: 2603, name: "Staff of Evil Spirits", category: "weapon", grade: "B", type: "magic" },
    { id: 2604, name: "Blood Tornado", category: "weapon", grade: "B", type: "two_sword" },
    { id: 2605, name: "Deadman's Glory Dual", category: "weapon", grade: "B", type: "dual" },
    { id: 2606, name: "Zubei's One-Handed Sword", category: "weapon", grade: "B", type: "sword" },
    { id: 2607, name: "Great Sword", category: "weapon", grade: "B", type: "two_sword" },
    { id: 2608, name: "Guardian Sword", category: "weapon", grade: "B", type: "sword" },
    { id: 2609, name: "Behemoth's Tuning Fork", category: "weapon", grade: "B", type: "blunt" },

    // ══ ARMAS ADICIONALES — Grado A ═════════════════════════
    { id: 2620, name: "Majestic Dual Sword", category: "weapon", grade: "A", type: "dual" },
    { id: 2621, name: "Tallum Blade (Dual)", category: "weapon", grade: "A", type: "dual" },
    { id: 2622, name: "Dark Legion's Edge (A)", category: "weapon", grade: "A", type: "two_sword" },
    { id: 2623, name: "Samurai Long Sword", category: "weapon", grade: "A", type: "sword" },
    { id: 2624, name: "Samurai Long Sword*2", category: "weapon", grade: "A", type: "dual" },
    { id: 2625, name: "Sword of Knowledge", category: "weapon", grade: "A", type: "sword" },
    { id: 2626, name: "Requiem", category: "weapon", grade: "A", type: "magic" },
    { id: 2627, name: "Revolver of Dawn", category: "weapon", grade: "A", type: "magic" },
    { id: 2628, name: "Shining Edge", category: "weapon", grade: "A", type: "sword" },
    { id: 2629, name: "Basalt Battlehammer (Dual Blunt)", category: "weapon", grade: "A", type: "blunt" },

    // ══ ARMAS ADICIONALES — Grado S ═════════════════════════
    { id: 2640, name: "Icarus Sawsword", category: "weapon", grade: "S", type: "two_sword" },
    { id: 2641, name: "Icarus Hammer", category: "weapon", grade: "S", type: "blunt" },
    { id: 2642, name: "Icarus Trident", category: "weapon", grade: "S", type: "spear" },
    { id: 2643, name: "Icarus Wingblade", category: "weapon", grade: "S", type: "sword" },
    { id: 2644, name: "Icarus Dagger", category: "weapon", grade: "S", type: "dagger" },
    { id: 2645, name: "Dual Angel Slayer", category: "weapon", grade: "S", type: "dual" },
    { id: 2646, name: "Dual Demon Dagger", category: "weapon", grade: "S", type: "dual" },
    { id: 2647, name: "Dual Forgotten Blade", category: "weapon", grade: "S", type: "dual" },
    { id: 2648, name: "Forgotten Blade (Two-Handed)", category: "weapon", grade: "S", type: "two_sword" },
    { id: 2649, name: "Heaven's Divider (Dual)", category: "weapon", grade: "S", type: "dual" },

    // ══ ARMAS ADICIONALES — Grado S80 ═══════════════════════
    { id: 2660, name: "Vesper Stormer", category: "weapon", grade: "S80", type: "spear" },
    { id: 2661, name: "Vesper Avenger", category: "weapon", grade: "S80", type: "two_sword" },
    { id: 2662, name: "Vesper Master", category: "weapon", grade: "S80", type: "blunt" },
    { id: 2663, name: "Vesper Dual Sword", category: "weapon", grade: "S80", type: "dual" },
    { id: 2664, name: "Vesper Dual Cutter", category: "weapon", grade: "S80", type: "dual" },

    // ══ ARMAS ADICIONALES — Grado S84 ═══════════════════════
    { id: 2680, name: "Vorpal Slasher", category: "weapon", grade: "S84", type: "two_sword" },
    { id: 2681, name: "Vorpal Splitter", category: "weapon", grade: "S84", type: "blunt" },
    { id: 2682, name: "Vorpal Spear", category: "weapon", grade: "S84", type: "spear" },
    { id: 2683, name: "Vorpal Dual Blades", category: "weapon", grade: "S84", type: "dual" },
    { id: 2684, name: "Vorpal Edge", category: "weapon", grade: "S84", type: "sword" },

    // ══ MATERIALES ADICIONALES ══════════════════════════════
    { id: 2700, name: "Sealed Imperial Crusader Belt", category: "material", grade: "S", type: "part" },
    { id: 2701, name: "Sealed Draconic Leather Belt", category: "material", grade: "S", type: "part" },
    { id: 2702, name: "Sealed Arcana Sapphire", category: "material", grade: "S", type: "part" },
    { id: 2703, name: "Forgotten Blade Edge", category: "material", grade: "S", type: "part" },
    { id: 2704, name: "Heaven's Divider Edge", category: "material", grade: "S", type: "part" },
    { id: 2705, name: "Draconic Bow Shaft", category: "material", grade: "S", type: "part" },
    { id: 2706, name: "Angel Slayer Blade", category: "material", grade: "S", type: "part" },
    { id: 2707, name: "Arcana Mace Head", category: "material", grade: "S", type: "part" },
    { id: 2708, name: "Imperial Crusader Breastplate Part", category: "material", grade: "S", type: "part" },
    { id: 2709, name: "Imperial Crusader Gaiters Part", category: "material", grade: "S", type: "part" },
    { id: 2710, name: "Draconic Leather Armor Part", category: "material", grade: "S", type: "part" },
    { id: 2711, name: "Arcana Robe Part", category: "material", grade: "S", type: "part" },
    { id: 2712, name: "Vesper Breastplate Part", category: "material", grade: "S80", type: "part" },
    { id: 2713, name: "Vesper Leather Armor Part", category: "material", grade: "S80", type: "part" },
    { id: 2714, name: "Vesper Robe Part", category: "material", grade: "S80", type: "part" },
    { id: 2715, name: "Vesper Sword Piece", category: "material", grade: "S80", type: "part" },
    { id: 2716, name: "Vorpal Breastplate Part", category: "material", grade: "S84", type: "part" },
    { id: 2717, name: "Vorpal Leather Armor Part", category: "material", grade: "S84", type: "part" },
    { id: 2718, name: "Vorpal Robe Part", category: "material", grade: "S84", type: "part" },
    { id: 2719, name: "Vorpal Sword Piece", category: "material", grade: "S84", type: "part" },
    { id: 2720, name: "Steel", category: "material", grade: "", type: "resource" },
    { id: 2721, name: "Cokes", category: "material", grade: "", type: "resource" },
    { id: 2722, name: "Warsmith's Mold", category: "material", grade: "", type: "resource" },
    { id: 2723, name: "Mineral Water", category: "material", grade: "", type: "resource" },
    { id: 2724, name: "High-grade Suede", category: "material", grade: "", type: "resource" },
    { id: 2725, name: "Moonstone Earring Beads", category: "material", grade: "B", type: "part" },
    { id: 2726, name: "Necklace of Valakas Pattern", category: "material", grade: "S", type: "part" },
    { id: 2727, name: "Earring of Antharas Pattern", category: "material", grade: "S", type: "part" },
    { id: 2728, name: "Ring of Baium Pattern", category: "material", grade: "S", type: "part" },
    { id: 2729, name: "Earring of Zaken Pattern", category: "material", grade: "S", type: "part" },
    { id: 2730, name: "Major Arcana Piece", category: "material", grade: "S", type: "part" },
    { id: 2731, name: "Crystal S80", category: "material", grade: "S80", type: "crystal" },
    { id: 2732, name: "Crystal S84", category: "material", grade: "S84", type: "crystal" },

    // ══ SCROLLS ADICIONALES ══════════════════════════════════
    { id: 2800, name: "Scroll: Enchant Weapon S80", category: "scroll", grade: "S80", type: "enchant" },
    { id: 2801, name: "Scroll: Enchant Armor S80", category: "scroll", grade: "S80", type: "enchant" },
    { id: 2802, name: "Scroll: Enchant Weapon S84", category: "scroll", grade: "S84", type: "enchant" },
    { id: 2803, name: "Scroll: Enchant Armor S84", category: "scroll", grade: "S84", type: "enchant" },
    { id: 2804, name: "Blessed Scroll: Enchant Weapon S80", category: "scroll", grade: "S80", type: "enchant" },
    { id: 2805, name: "Blessed Scroll: Enchant Armor S80", category: "scroll", grade: "S84", type: "enchant" },
    { id: 2806, name: "Scroll: Enchant Weapon B", category: "scroll", grade: "B", type: "enchant" },
    { id: 2807, name: "Scroll: Enchant Armor B", category: "scroll", grade: "B", type: "enchant" },
    { id: 2808, name: "Scroll of Ancient Knowledge", category: "scroll", grade: "", type: "skill_book" },
    { id: 2809, name: "Spellbook: Heroic Valor", category: "scroll", grade: "", type: "skill_book" },
    { id: 2810, name: "Spellbook: Vengeance", category: "scroll", grade: "", type: "skill_book" },
    { id: 2811, name: "Spellbook: Resurrection on Site", category: "scroll", grade: "", type: "skill_book" },
    { id: 2812, name: "Spellbook: Pa'agrian's Power", category: "scroll", grade: "", type: "skill_book" },
    { id: 2813, name: "Spellbook: Evasion Stance", category: "scroll", grade: "", type: "skill_book" },
    { id: 2814, name: "Spellbook: Celestial Shield", category: "scroll", grade: "", type: "skill_book" },
    { id: 2815, name: "Spellbook: Shield of Faith", category: "scroll", grade: "", type: "skill_book" },
    { id: 2816, name: "Spellbook: Arcane Chaos", category: "scroll", grade: "", type: "skill_book" },
    { id: 2817, name: "Spellbook: Chain Hydra", category: "scroll", grade: "", type: "skill_book" },

    // ══ CONSUMIBLES ADICIONALES ══════════════════════════════
    { id: 2900, name: "Blessed Soulshot S-Grade", category: "consumable", grade: "S", type: "shot" },
    { id: 2901, name: "Blessed Soulshot A-Grade", category: "consumable", grade: "A", type: "shot" },
    { id: 2902, name: "Fish Stew (HP Recovery)", category: "consumable", grade: "", type: "food" },
    { id: 2903, name: "High-grade CP Potion", category: "consumable", grade: "", type: "potion" },
    { id: 2904, name: "Elixir of CP (B)", category: "consumable", grade: "B", type: "elixir" },
    { id: 2905, name: "Elixir of HP (A)", category: "consumable", grade: "A", type: "elixir" },
    { id: 2906, name: "Elixir of HP (S)", category: "consumable", grade: "S", type: "elixir" },
    { id: 2907, name: "Elixir of MP (A)", category: "consumable", grade: "A", type: "elixir" },
    { id: 2908, name: "Elixir of MP (S)", category: "consumable", grade: "S", type: "elixir" },
    { id: 2909, name: "Fishing Shot", category: "consumable", grade: "", type: "shot" },
    { id: 2910, name: "Morai Crystal Shard", category: "consumable", grade: "", type: "event" },

    // ══ ESPECIALES ADICIONALES ═══════════════════════════════
    { id: 2950, name: "Talisman of Speed", category: "special", grade: "", type: "talisman" },
    { id: 2951, name: "Talisman of Protection", category: "special", grade: "", type: "talisman" },
    { id: 2952, name: "Talisman of Aden", category: "special", grade: "", type: "talisman" },
    { id: 2953, name: "Frintezza's Trophy", category: "special", grade: "", type: "boss_drop" },
    { id: 2954, name: "Cabrio's Hand", category: "special", grade: "", type: "boss_drop" },
    { id: 2955, name: "Hallate's Medallion", category: "special", grade: "", type: "boss_drop" },
    { id: 2956, name: "Kernon's Molar", category: "special", grade: "", type: "boss_drop" },
    { id: 2957, name: "Golkonda's Spinal Cord", category: "special", grade: "", type: "boss_drop" },
    { id: 2958, name: "Antharas Scale", category: "special", grade: "", type: "boss_drop" },
    { id: 2959, name: "Valakas Scale", category: "special", grade: "", type: "boss_drop" },
    { id: 2960, name: "Lindvior Scale", category: "special", grade: "", type: "boss_drop" },
    { id: 2961, name: "Ekimus Skull", category: "special", grade: "", type: "boss_drop" },
    { id: 2962, name: "Wooden Caretaker Medal", category: "special", grade: "", type: "event" },
    { id: 2963, name: "Hero Coin", category: "special", grade: "", type: "hero" },
    { id: 2964, name: "Clan Arena Insignia", category: "special", grade: "", type: "clan" },
    { id: 2965, name: "Attribute Stone (Fire)", category: "special", grade: "", type: "attribute" },
    { id: 2966, name: "Attribute Stone (Water)", category: "special", grade: "", type: "attribute" },
    { id: 2967, name: "Attribute Stone (Wind)", category: "special", grade: "", type: "attribute" },
    { id: 2968, name: "Attribute Stone (Earth)", category: "special", grade: "", type: "attribute" },
    { id: 2969, name: "Attribute Stone (Holy)", category: "special", grade: "", type: "attribute" },
    { id: 2970, name: "Attribute Stone (Dark)", category: "special", grade: "", type: "attribute" },
    { id: 2971, name: "Rough Jewel (Fire)", category: "special", grade: "", type: "attribute" },
    { id: 2972, name: "Rough Jewel (Water)", category: "special", grade: "", type: "attribute" },
    { id: 2973, name: "Rough Jewel (Wind)", category: "special", grade: "", type: "attribute" },
    { id: 2974, name: "Rough Jewel (Earth)", category: "special", grade: "", type: "attribute" },
    { id: 2975, name: "Rough Jewel (Holy)", category: "special", grade: "", type: "attribute" },
    { id: 2976, name: "Rough Jewel (Dark)", category: "special", grade: "", type: "attribute" },
    { id: 2977, name: "Mid-grade Life Stone (Lv.80)", category: "special", grade: "", type: "life_stone" },
    { id: 2978, name: "High-grade Life Stone (Lv.80)", category: "special", grade: "", type: "life_stone" },
    { id: 2979, name: "Top-grade Life Stone (Lv.80)", category: "special", grade: "", type: "life_stone" },
    { id: 2980, name: "Soul Crystal Stage 13 - Red", category: "special", grade: "", type: "soul_crystal" },
    { id: 2981, name: "Soul Crystal Stage 13 - Blue", category: "special", grade: "", type: "soul_crystal" },
    { id: 2982, name: "Soul Crystal Stage 13 - Green", category: "special", grade: "", type: "soul_crystal" },
    { id: 2983, name: "Sealed Talisman of Baium", category: "special", grade: "", type: "talisman" },
    { id: 2984, name: "Dragon Heart", category: "special", grade: "", type: "boss_drop" },
    { id: 2985, name: "Olympiad Bracelet (Hero)", category: "special", grade: "", type: "olympiad" },
    { id: 2986, name: "Icarus Equipment Box", category: "special", grade: "S", type: "event" },
    { id: 2987, name: "Vesper Equipment Box", category: "special", grade: "S80", type: "event" },
    { id: 2988, name: "Vorpal Equipment Box", category: "special", grade: "S84", type: "event" },

    // ══ RECETAS ADICIONALES ══════════════════════════════════
    { id: 2850, name: "Recipe: Vesper Armor", category: "recipe", grade: "S80", type: "armor_recipe" },
    { id: 2851, name: "Recipe: Vesper Leather Armor", category: "recipe", grade: "S80", type: "armor_recipe" },
    { id: 2852, name: "Recipe: Vesper Robe", category: "recipe", grade: "S80", type: "armor_recipe" },
    { id: 2853, name: "Recipe: Vorpal Armor", category: "recipe", grade: "S84", type: "armor_recipe" },
    { id: 2854, name: "Recipe: Vorpal Leather Armor", category: "recipe", grade: "S84", type: "armor_recipe" },
    { id: 2855, name: "Recipe: Vorpal Robe", category: "recipe", grade: "S84", type: "armor_recipe" },
    { id: 2856, name: "Recipe: Vorpal Sword", category: "recipe", grade: "S84", type: "weapon_recipe" },
    { id: 2857, name: "Recipe: Vorpal Bow", category: "recipe", grade: "S84", type: "weapon_recipe" },
    { id: 2858, name: "Recipe: Icarus Hammer", category: "recipe", grade: "S", type: "weapon_recipe" },
    { id: 2859, name: "Recipe: Icarus Spitter", category: "recipe", grade: "S", type: "weapon_recipe" },
    { id: 2860, name: "Recipe: Icarus Trident", category: "recipe", grade: "S", type: "weapon_recipe" },
    { id: 2861, name: "Recipe: Crystal A-Grade", category: "recipe", grade: "A", type: "material_recipe" },
    { id: 2862, name: "Recipe: Crystal S-Grade", category: "recipe", grade: "S", type: "material_recipe" },

    // ══ JOYAS ESPECIALES / RAID BOSS ════════════════════════
    // Tateossian (grado B — muy valorados)
    { id: 3000, name: "Tateossian Necklace", category: "jewelry", grade: "B", type: "necklace" },
    { id: 3001, name: "Tateossian Earring", category: "jewelry", grade: "B", type: "earring" },
    { id: 3002, name: "Tateossian Ring", category: "jewelry", grade: "B", type: "ring" },

    // Moonstone (grado B)
    { id: 3010, name: "Moonstone Earring", category: "jewelry", grade: "B", type: "earring" },
    { id: 3011, name: "Moonstone Necklace", category: "jewelry", grade: "B", type: "necklace" },
    { id: 3012, name: "Moonstone Ring", category: "jewelry", grade: "B", type: "ring" },

    // Grado A — Más joyas
    { id: 3020, name: "Necklace of Aden", category: "jewelry", grade: "A", type: "necklace" },
    { id: 3021, name: "Earring of Aden", category: "jewelry", grade: "A", type: "earring" },
    { id: 3022, name: "Ring of Aden", category: "jewelry", grade: "A", type: "ring" },
    { id: 3023, name: "Necklace of Authority", category: "jewelry", grade: "A", type: "necklace" },
    { id: 3024, name: "Earring of Authority", category: "jewelry", grade: "A", type: "earring" },
    { id: 3025, name: "Ring of Authority", category: "jewelry", grade: "A", type: "ring" },

    // Grado S — Joyas boss drop adicionales
    { id: 3030, name: "Earring of Beleth", category: "jewelry", grade: "S", type: "earring" },
    { id: 3031, name: "Ring of Beleth", category: "jewelry", grade: "S", type: "ring" },
    { id: 3032, name: "Necklace of Beleth", category: "jewelry", grade: "S", type: "necklace" },
    { id: 3033, name: "Ring of Freya", category: "jewelry", grade: "S84", type: "ring" },
    { id: 3034, name: "Earring of Freya", category: "jewelry", grade: "S84", type: "earring" },
    { id: 3035, name: "Necklace of Freya", category: "jewelry", grade: "S84", type: "necklace" },

    // ══ ARMADURAS GRADO C — SETS ADICIONALES ═══════════════
    // Set Avadon completo ya existe. Agregamos más C-grade:
    { id: 3100, name: "Demon's Robe", category: "armor", grade: "C", type: "robe" },
    { id: 3101, name: "Demon's Tunic", category: "armor", grade: "C", type: "robe" },
    { id: 3102, name: "Demon's Stockings", category: "armor", grade: "C", type: "robe" },
    { id: 3103, name: "Demon's Gloves", category: "armor", grade: "C", type: "gloves" },
    { id: 3104, name: "Demon's Sandals", category: "armor", grade: "C", type: "boots" },
    { id: 3110, name: "Mithril Scale Breastplate", category: "armor", grade: "C", type: "light" },
    { id: 3111, name: "Mithril Scale Gaiters", category: "armor", grade: "C", type: "light" },
    { id: 3112, name: "Mithril Scale Helmet", category: "armor", grade: "C", type: "light" },
    { id: 3113, name: "Mithril Scale Gloves", category: "armor", grade: "C", type: "gloves" },
    { id: 3114, name: "Mithril Scale Boots", category: "armor", grade: "C", type: "boots" },
    { id: 3120, name: "Plated Leather Armor", category: "armor", grade: "C", type: "light" },
    { id: 3121, name: "Plated Leather Gaiters", category: "armor", grade: "C", type: "light" },
    { id: 3122, name: "Plated Leather Helmet", category: "armor", grade: "C", type: "light" },
    { id: 3123, name: "Plated Leather Gloves", category: "armor", grade: "C", type: "gloves" },
    { id: 3124, name: "Plated Leather Boots", category: "armor", grade: "C", type: "boots" },

    // ══ ARMADURAS GRADO D — SETS ════════════════════════════
    { id: 3200, name: "Chain Mail Armor", category: "armor", grade: "D", type: "heavy" },
    { id: 3201, name: "Chain Mail Helmet", category: "armor", grade: "D", type: "heavy" },
    { id: 3202, name: "Chain Mail Shield", category: "armor", grade: "D", type: "shield" },
    { id: 3203, name: "Chain Mail Gloves", category: "armor", grade: "D", type: "gloves" },
    { id: 3204, name: "Chain Mail Boots", category: "armor", grade: "D", type: "boots" },
    { id: 3210, name: "Scale Mail Armor", category: "armor", grade: "D", type: "light" },
    { id: 3211, name: "Scale Mail Helmet", category: "armor", grade: "D", type: "light" },
    { id: 3212, name: "Scale Mail Gloves", category: "armor", grade: "D", type: "gloves" },
    { id: 3213, name: "Scale Mail Boots", category: "armor", grade: "D", type: "boots" },
    { id: 3220, name: "Mithril Tunic", category: "armor", grade: "D", type: "robe" },
    { id: 3221, name: "Mithril Stockings", category: "armor", grade: "D", type: "robe" },
    { id: 3222, name: "Mithril Gloves", category: "armor", grade: "D", type: "gloves" },
    { id: 3223, name: "Mithril Boots", category: "armor", grade: "D", type: "boots" },

    // ══ ARMAS GRADO D/C ADICIONALES ═════════════════════════
    { id: 3300, name: "Stiletto", category: "weapon", grade: "D", type: "dagger" },
    { id: 3301, name: "Short Sword", category: "weapon", grade: "D", type: "sword" },
    { id: 3302, name: "Long Sword", category: "weapon", grade: "D", type: "sword" },
    { id: 3303, name: "Falchion", category: "weapon", grade: "D", type: "sword" },
    { id: 3304, name: "Mace", category: "weapon", grade: "D", type: "blunt" },
    { id: 3305, name: "Staff", category: "weapon", grade: "D", type: "magic" },
    { id: 3306, name: "Short Bow", category: "weapon", grade: "D", type: "bow" },
    { id: 3310, name: "Bone Blade", category: "weapon", grade: "C", type: "dagger" },
    { id: 3311, name: "Sword of Damascus", category: "weapon", grade: "C", type: "sword" },
    { id: 3312, name: "Bellion Cestus", category: "weapon", grade: "C", type: "fist" },
    { id: 3313, name: "Akat Blunt Weapon", category: "weapon", grade: "C", type: "blunt" },
    { id: 3314, name: "Spear of Pa'agrian", category: "weapon", grade: "C", type: "spear" },

    // ══ PIEZAS DE CRAFTEO (Parts) ADICIONALES ═══════════════
    { id: 3400, name: "Tateossian Necklace Gem", category: "material", grade: "B", type: "part" },
    { id: 3401, name: "Tateossian Earring Gem", category: "material", grade: "B", type: "part" },
    { id: 3402, name: "Tateossian Ring Gem", category: "material", grade: "B", type: "part" },
    { id: 3403, name: "Moonstone Shard", category: "material", grade: "B", type: "part" },
    { id: 3404, name: "Majestic Necklace Beads", category: "material", grade: "A", type: "part" },
    { id: 3405, name: "Majestic Earring Gem", category: "material", grade: "A", type: "part" },
    { id: 3406, name: "Majestic Ring Gem", category: "material", grade: "A", type: "part" },
    { id: 3407, name: "Blue Wolf Necklace Beads", category: "material", grade: "B", type: "part" },
    { id: 3408, name: "Blue Wolf Earring Gem", category: "material", grade: "B", type: "part" },
    { id: 3409, name: "Blue Wolf Ring Gem", category: "material", grade: "B", type: "part" },
    { id: 3410, name: "Tallum Plate Armor Part", category: "material", grade: "A", type: "part" },
    { id: 3411, name: "Dark Crystal Armor Part", category: "material", grade: "A", type: "part" },
    { id: 3412, name: "Majestic Plate Armor Part", category: "material", grade: "A", type: "part" },
    { id: 3413, name: "Icarus Wingblade Piece", category: "material", grade: "S", type: "part" },
    { id: 3414, name: "Icarus Dagger Blade", category: "material", grade: "S", type: "part" },
    { id: 3415, name: "Icarus Sawsword Blade", category: "material", grade: "S", type: "part" },

    // ══ MATERIALES RAROS / RAID ══════════════════════════════
    { id: 3500, name: "Scale of Drake", category: "material", grade: "", type: "resource" },
    { id: 3501, name: "Drake Egg", category: "material", grade: "", type: "resource" },
    { id: 3502, name: "Giant Codex of Mastery", category: "material", grade: "", type: "spellbook" },
    { id: 3503, name: "Enchanted NM Fiber", category: "material", grade: "", type: "resource" },
    { id: 3504, name: "Piety's Stone", category: "material", grade: "", type: "key_material" },
    { id: 3505, name: "Brimstone", category: "material", grade: "", type: "resource" },
    { id: 3506, name: "Mithril Alloy", category: "material", grade: "", type: "resource" },
    { id: 3507, name: "Oriharukon", category: "material", grade: "", type: "resource" },
    { id: 3508, name: "Adamantite", category: "material", grade: "", type: "resource" },
    { id: 3509, name: "Varnish of Purity", category: "material", grade: "", type: "key_material" },
    { id: 3510, name: "Iron Alloy", category: "material", grade: "", type: "resource" },
    { id: 3511, name: "Metallic Fiber", category: "material", grade: "", type: "resource" },

    // ══ CONSUMIBLES ADICIONALES ══════════════════════════════
    { id: 3600, name: "Soulshot S80-Grade", category: "consumable", grade: "S80", type: "shot" },
    { id: 3601, name: "Spiritshot S80-Grade", category: "consumable", grade: "S80", type: "shot" },
    { id: 3602, name: "Blessed Spiritshot S80", category: "consumable", grade: "S80", type: "shot" },
    { id: 3603, name: "Soulshot S84-Grade", category: "consumable", grade: "S84", type: "shot" },
    { id: 3604, name: "Spiritshot S84-Grade", category: "consumable", grade: "S84", type: "shot" },
    { id: 3605, name: "Blessed Spiritshot S84", category: "consumable", grade: "S84", type: "shot" },
    { id: 3606, name: "HP Recovery Potion (Large)", category: "consumable", grade: "", type: "potion" },
    { id: 3607, name: "MP Recovery Potion (Large)", category: "consumable", grade: "", type: "potion" },
    { id: 3608, name: "Antidote", category: "consumable", grade: "", type: "potion" },
    { id: 3609, name: "Speed Potion", category: "consumable", grade: "", type: "potion" },

    // ══ ARMAS GRADO A — Más tipos ════════════════════════════
    { id: 3700, name: "Dynasty Spear", category: "weapon", grade: "A", type: "spear" },
    { id: 3701, name: "Dynasty Mahiron", category: "weapon", grade: "A", type: "dual" },
    { id: 3702, name: "Meteor Shower Orb", category: "weapon", grade: "A", type: "magic" },
    { id: 3703, name: "Sword of Authority", category: "weapon", grade: "A", type: "sword" },
    { id: 3704, name: "Tallum One-Handed Sword", category: "weapon", grade: "A", type: "sword" },
    { id: 3705, name: "Dark Legion's Edge", category: "weapon", grade: "A", type: "two_sword" },
    { id: 3706, name: "Crystal Bow", category: "weapon", grade: "A", type: "bow" },
    { id: 3707, name: "Demon Dagger (A-grade)", category: "weapon", grade: "A", type: "dagger" },

    // ══ ARMAS S — Más variantes (Icarus full) ════════════════
    { id: 3710, name: "Icarus Hall (Spiritstaff)", category: "weapon", grade: "S", type: "magic" },
    { id: 3711, name: "Icarus Disperser (Bow)", category: "weapon", grade: "S", type: "bow" },
    { id: 3712, name: "Raphael's Roar (Mace)", category: "weapon", grade: "S", type: "blunt" },
    { id: 3713, name: "Demon Dagger (S-grade)", category: "weapon", grade: "S", type: "dagger" },

    // ══ RECETAS ADICIONALES ══════════════════════════════════
    { id: 3800, name: "Recipe: Tateossian Necklace", category: "recipe", grade: "B", type: "jewel_recipe" },
    { id: 3801, name: "Recipe: Tateossian Earring", category: "recipe", grade: "B", type: "jewel_recipe" },
    { id: 3802, name: "Recipe: Tateossian Ring", category: "recipe", grade: "B", type: "jewel_recipe" },
    { id: 3803, name: "Recipe: Majestic Necklace", category: "recipe", grade: "A", type: "jewel_recipe" },
    { id: 3804, name: "Recipe: Majestic Earrings", category: "recipe", grade: "A", type: "jewel_recipe" },
    { id: 3805, name: "Recipe: Majestic Ring", category: "recipe", grade: "A", type: "jewel_recipe" },
    { id: 3806, name: "Recipe: Tallum Plate Armor", category: "recipe", grade: "A", type: "armor_recipe" },
    { id: 3807, name: "Recipe: Dark Crystal Armor", category: "recipe", grade: "A", type: "armor_recipe" },
    { id: 3808, name: "Recipe: Majestic Plate Armor", category: "recipe", grade: "A", type: "armor_recipe" },
    { id: 3809, name: "Recipe: Blue Wolf Necklace", category: "recipe", grade: "B", type: "jewel_recipe" },
    { id: 3810, name: "Recipe: Blue Wolf Earrings", category: "recipe", grade: "B", type: "jewel_recipe" },
    { id: 3811, name: "Recipe: Blue Wolf Ring", category: "recipe", grade: "B", type: "jewel_recipe" },
    { id: 3812, name: "Recipe: Doom Plate Armor", category: "recipe", grade: "B", type: "armor_recipe" },
    { id: 3813, name: "Recipe: Zubei's Armor", category: "recipe", grade: "B", type: "armor_recipe" },
    { id: 3814, name: "Recipe: Blue Wolf Breastplate", category: "recipe", grade: "B", type: "armor_recipe" },
];


// Helper: buscar items por nombre (case-insensitive)
export function searchItems(query) {
    if (!query || query.length < 2) return [];
    const q = query.toLowerCase();
    if (window.STATE && window.STATE.globalItems && window.STATE.globalItems.length > 0) {
        return window.STATE.globalItems.filter(item => item.name.toLowerCase().includes(q)).slice(0, 20);
    }
    return L2_ITEMS.filter(item => item.name.toLowerCase().includes(q)).slice(0, 20);
}

// Helper: obtener todos los items de una categoría
export function getItemsByCategory(category) {
    return L2_ITEMS.filter(item => item.category === category);
}

// Helper: etiqueta de grado con color
export const GRADE_COLORS = {
    "NG": "#aaaaaa",
    "D": "#8888ff",
    "C": "#88cc88",
    "B": "#ffcc00",
    "A": "#ff8844",
    "S": "#ff4444",
    "S80": "#ff6688",
    "S84": "#ff22aa",
    "": "#aaaaaa",
};

export const CATEGORY_LABELS = {
    adena: "Adena",
    weapon: "Arma",
    armor: "Armadura",
    jewelry: "Joya",
    material: "Material",
    recipe: "Receta",
    recipe_weapon: "Receta/Arma",
    recipe_armor: "Receta/Armadura",
    recipe_jewelry: "Receta/Joyería",
    consumable: "Consumible",
    scroll: "Scroll",
    special: "Especial",
};
